### ISSUE TITLE
你们的upload组件到底怎么将图片数据回显？

### ISSUE THREAD

**Issue by Zebra-web** [umicro/uView#1011]
官方文档的说明和右侧示例完全对不上，数据回显的方法也没有讲

**Comment by yaojin2070** [comment]
自定义就好了
![image](https://user-images.githubusercontent.com/48686959/124103890-4efab400-da94-11eb-9eab-9061c417fa99.png)

**Comment by Zebra-web** [comment]
> 自定义就好了
> ![image](https://user-images.githubusercontent.com/48686959/124103890-4efab400-da94-11eb-9eab-9061c417fa99.png)
能讲一下思路吗？

**Comment by Zebra-web** [comment]
> 自定义就好了
能讲一下思路吗

**Comment by yaojin2070** [comment]
`
<template>
	<view>
		<view class="img-setting-content">
			<view v-for="(item, index) in images" :key="item" style="display: inline-block;" class="img-wrap">
				<u-image @click="seeImg(item)" style="display: inline-block;margin-right: 13rpx;" width="150rpx"
					height="150rpx" :key="item" :src="item" mode="aspectFill">
				</u-image>
				<view v-if="canDelete" class="u-delete-icon" @click.stop="deleteItem(item, 'images')">
					<u-icon class="u-icon" name="close" size="20"></u-icon>
				</view>
			</view>

			<view v-if="showUpload" style="display: inline-block;">
				<u-upload @on-success="upLoadSuccess" :header="{'access-token': userInfo.access_token}" ref="upload"
					:show-upload-list="false" :custom-btn="true" :action="uploadAction">
					<view slot="addBtn">
						<view class="u-list-item u-add-wrap" hover-class="u-add-wrap__hover" hover-stay-time="150"
							:style="{
						width: '150rpx',
						height: '150rpx'
					}">
							<u-icon name="plus" class="u-add-btn" size="40"></u-icon>
						</view>
					</view>
				</u-upload>
			</view>
		</view>

	</view>
</template>

<script>
	import {
		mapState
	} from 'vuex'
	export default {
		props: {
			/* 之前的图片 */
			beforeImgArr: {
				type: Array,
				default: () => []
			},
			/* 上传的地址 */
			action: {
				type: String,
				default: ''
			},
			/* 是否可以上传图片 */
			showUpload: {
				type: Boolean,
				default: true
			},
			/* 是否可以删除图片 */
			canDelete: {
				type: Boolean,
				default: true
			}
		},
		computed: {
			...mapState({
				userInfo: state => state.userInfo,
				isClient: state => state.isClient
			})
		},
		data() {
			return {
				images: [],
				uploadAction: ''
			}
		},
		created() {
			this.images = this.$u.deepMerge(this.beforeImgArr)
			if (this.isClient) {
				this.uploadAction = `http://192.168.110.236:8090/custom/${this.action}`
			} else {
				this.uploadAction = `http://192.168.110.236:8090/api/${this.action}`
			}
			// if (process.env.NODE_ENV === 'development') {
			// 	if (this.isClient) {
			// 		this.uploadAction = `http://192.168.110.236:8090/custom/${this.action}`
			// 	} else {
			// 		this.uploadAction = `http://192.168.110.236:8090/api/${this.action}`
			// 	}

			// } else {
			// 	console.log('shegnchang ')
			// }
		},
		watch: {
			beforeImgArr(value) {
				this.images = this.$u.deepMerge(value)
			}
		},
		methods: {
			/* 查看图片 */
			seeImg(url) {
				uni.previewImage({
					urls: [url]
				})
			},
			/* 图片上传成功后 */
			upLoadSuccess(res, index, lists, name) {
				this.images = this.images.concat(res.data)
				this.$emit('success', this.images)
			},
			/* 删除某个图片后 */
			deleteItem(imgPath, type) {
				this.images = this.images.filter(item => item !== imgPath)
				this.$emit('success', this.images)
			},
		}
	}
</script>

<style lang="scss" scoped>
	.u-list-item {
		width: 150rpx;
		height: 150rpx;
		overflow: hidden;
		// margin: 10rpx;
		background: rgb(244, 245, 246);
		position: relative;
		border-radius: 10rpx;
		/* #ifndef APP-NVUE */
		// display: flex;
		text-align: center;
		line-height: 150rpx;
		/* #endif */
		align-items: center;
		justify-content: center;
		display: inline-block;
	}

	.u-add-wrap {
		flex-direction: column;
		color: #606266;
		font-size: 26rpx;
	}

	.u-add-wrap__hover {
		background-color: rgb(235, 236, 238);
	}

	.img-setting-content {
		display: inline-block;


		.img-wrap {
			position: relative;
			display: inline-block;
		}

		.img-class {

			width: 150rpx;
			height: 150rpx;
			margin-right: 13rpx;

		}

		.u-delete-icon {
			position: absolute;
			top: 12rpx;
			right: 20rpx;
			z-index: 10;
			background-color: #fff;
			border-radius: 100rpx;
			width: 33rpx;
			height: 33rpx;
			display: flex;
			flex-direction: row;
			align-items: center;
			justify-content: center;
		}
	}
</style>

`

代码直接给你, 写得不咋地, 你可以优化下

**Comment by yaojin2070** [comment]
`
<template>
	<view>
		<view class="img-setting-content">
			<view v-for="(item, index) in images" :key="item" style="display: inline-block;" class="img-wrap">
				<u-image @click="seeImg(item)" style="display: inline-block;margin-right: 13rpx;" width="150rpx"
					height="150rpx" :key="item" :src="item" mode="aspectFill">
				</u-image>
				<view v-if="canDelete" class="u-delete-icon" @click.stop="deleteItem(item, 'images')">
					<u-icon class="u-icon" name="close" size="20"></u-icon>
				</view>
			</view>

			<view v-if="showUpload" style="display: inline-block;">
				<u-upload @on-success="upLoadSuccess" :header="{'access-token': userInfo.access_token}" ref="upload"
					:show-upload-list="false" :custom-btn="true" :action="uploadAction">
					<view slot="addBtn">
						<view class="u-list-item u-add-wrap" hover-class="u-add-wrap__hover" hover-stay-time="150"
							:style="{
						width: '150rpx',
						height: '150rpx'
					}">
							<u-icon name="plus" class="u-add-btn" size="40"></u-icon>
						</view>
					</view>
				</u-upload>
			</view>
		</view>

	</view>
</template>


`

`
<script>
	import {
		mapState
	} from 'vuex'
	export default {
		props: {
			/* 之前的图片 */
			beforeImgArr: {
				type: Array,
				default: () => []
			},
			/* 上传的地址 */
			action: {
				type: String,
				default: ''
			},
			/* 是否可以上传图片 */
			showUpload: {
				type: Boolean,
				default: true
			},
			/* 是否可以删除图片 */
			canDelete: {
				type: Boolean,
				default: true
			}
		},
		computed: {
			...mapState({
				userInfo: state => state.userInfo,
				isClient: state => state.isClient
			})
		},
		data() {
			return {
				images: [],
				uploadAction: ''
			}
		},
		created() {
			this.images = this.$u.deepMerge(this.beforeImgArr)
			if (this.isClient) {
				this.uploadAction = `http://192.168.110.236:8090/custom/${this.action}`
			} else {
				this.uploadAction = `http://192.168.110.236:8090/api/${this.action}`
			}
			// if (process.env.NODE_ENV === 'development') {
			// 	if (this.isClient) {
			// 		this.uploadAction = `http://192.168.110.236:8090/custom/${this.action}`
			// 	} else {
			// 		this.uploadAction = `http://192.168.110.236:8090/api/${this.action}`
			// 	}

			// } else {
			// 	console.log('shegnchang ')
			// }
		},
		watch: {
			beforeImgArr(value) {
				this.images = this.$u.deepMerge(value)
			}
		},
		methods: {
			/* 查看图片 */
			seeImg(url) {
				uni.previewImage({
					urls: [url]
				})
			},
			/* 图片上传成功后 */
			upLoadSuccess(res, index, lists, name) {
				this.images = this.images.concat(res.data)
				this.$emit('success', this.images)
			},
			/* 删除某个图片后 */
			deleteItem(imgPath, type) {
				this.images = this.images.filter(item => item !== imgPath)
				this.$emit('success', this.images)
			},
		}
	}
</script>
`


`
<style lang="scss" scoped>
	.u-list-item {
		width: 150rpx;
		height: 150rpx;
		overflow: hidden;
		// margin: 10rpx;
		background: rgb(244, 245, 246);
		position: relative;
		border-radius: 10rpx;
		/* #ifndef APP-NVUE */
		// display: flex;
		text-align: center;
		line-height: 150rpx;
		/* #endif */
		align-items: center;
		justify-content: center;
		display: inline-block;
	}

	.u-add-wrap {
		flex-direction: column;
		color: #606266;
		font-size: 26rpx;
	}

	.u-add-wrap__hover {
		background-color: rgb(235, 236, 238);
	}

	.img-setting-content {
		display: inline-block;


		.img-wrap {
			position: relative;
			display: inline-block;
		}

		.img-class {

			width: 150rpx;
			height: 150rpx;
			margin-right: 13rpx;

		}

		.u-delete-icon {
			position: absolute;
			top: 12rpx;
			right: 20rpx;
			z-index: 10;
			background-color: #fff;
			border-radius: 100rpx;
			width: 33rpx;
			height: 33rpx;
			display: flex;
			flex-direction: row;
			align-items: center;
			justify-content: center;
		}
	}
</style>


`

代码可以看看

**Comment by Zebra-web** [comment]
> 代码可以看看
你这个业务上传的url是怎样的？是后端给你接口传图片还是你前端自己传？

**Comment by yaojin2070** [comment]
> > 代码可以看看
> > 你这个业务上传的url是怎样的？是后端给你接口传图片还是你前端自己传？

后端给接口, 自己传也是要接口吧,不然我放到哪里

**Comment by qq992064577** [comment]
请问一下uview怎么结合腾讯云COS对象存储使用

**Comment by yatoku** [comment]
> 官方文档的说明和右侧示例完全对不上，数据回显的方法也没有讲

右侧的示例在示例项目的代码中

**Comment by yatoku** [comment]
![image](https://user-images.githubusercontent.com/35695074/190945398-ef0605db-a7e8-4a5f-b9e4-bf0b039e56df.png)
