### ISSUE TITLE
请教问题：想了解下，uView的Demo工程中，哪里引入 page-nav组件的

### ISSUE THREAD

**Issue by hongtu1993** [umicro/uView#1025]
搜索了代码，没有发现有引入 /components/page-nav 组件的地方。easycom 也没有配置，好奇是怎么隐式引入的。

**Comment by hobeas** [comment]
因为他用了 easycom 且在 components 文件夹下

![image](https://user-images.githubusercontent.com/41267951/125426707-9f072afd-2bea-4516-b5a3-ab89c3805fb8.png)

**Comment by hongtu1993** [comment]
> 因为他用了 easycom 且在 components 文件夹下
> 
> ![image](https://user-images.githubusercontent.com/41267951/125426707-9f072afd-2bea-4516-b5a3-ab89c3805fb8.png)

谢谢您的回答。文档我没有细心看。
