### ISSUE TITLE
BUG: 关于深拷贝和深合并存在的一些问题

### ISSUE THREAD

**Issue by 2460392754** [umicro/uView#104]
## deepClone

无法正确处理的类型或内容，已下将需要克隆的对象命名为`target`

- 修改`target`原型或原型链
- 克隆类型为`Function`类型
- 克隆类型为`Object`对象上的原型链引用
- 克隆类型为`Object`的特殊对象
  - 例如：`Set`、`Map`、`WeakSet`、`WeakMap`、`RegExp`、`Date`等

## deepMerge

无法正确处理的类型或内容，已下将需要合并的对象命名为`target`和`source`

- 包含`deepClone`所有不能正常处理的情况

**Comment by BeiQiaoT** [comment]
> ## deepClone
> 无法正确处理的类型或内容，已下将需要克隆的对象命名为`target`
> 
> * 修改`target`原型或原型链
> * 克隆类型为`Function`类型
> * 克隆类型为`Object`对象上的原型链引用
> * 克隆类型为`Object`的特殊对象
>   
>   * 例如：`Set`、`Map`、`WeakSet`、`WeakMap`、`RegExp`、`Date`等
> 
> ## deepMerge
> 无法正确处理的类型或内容，已下将需要合并的对象命名为`target`和`source`
> 
> * 包含`deepClone`所有不能正常处理的情况

很深刻的见解，以截图提交

**Comment by 2460392754** [comment]
## deepMerge 补充

`source`对象中的`value`不能为null (没有进行处理)

**Comment by ZJH9Rondo** [comment]
所以为什么不能用lodash呢？你做这个deepClone和lodash里面的有什么区别？

**Comment by yatoku** [comment]
> 所以为什么不能用lodash呢？你做这个deepClone和lodash里面的有什么区别？

因为lodash太大了
