### ISSUE TITLE
u-tabs滑块某些状态下失效，位置错误且无法跟随current滑动

### ISSUE THREAD

**Issue by JHPCCOM** [umicro/uView#1046]
很奇怪，小程序在登录状态下u-tabs下方滑块正常滑动，当小程序未登录状态下，u-tabs下方滑块位置不对，且不会随着点击而移动，在调试工具appdata中current的数值正常，且页面script没有任何拦截行为
![image](https://user-images.githubusercontent.com/62272192/126733433-72778782-d56e-4674-97f7-414763ca0236.png)
![image](https://user-images.githubusercontent.com/62272192/126733444-e5fd07a4-4eb4-4b54-95ed-9ab5b509d613.png)
![image](https://user-images.githubusercontent.com/62272192/126733451-3901dd6e-1253-40fc-a54f-370dc16108d3.png)
手动修改current的值，u-tabs下方的滑块就会变正常。希望作者能帮忙看一下这个问题
![image](https://user-images.githubusercontent.com/62272192/126733477-24e51935-a032-402b-8afb-1ca8e4924326.png)

**Comment by JHPCCOM** [comment]
已解决，使用uniapp第三方路由uni-simple-router设置了首页的权限，页面内容都可以加载，偶然发现onLoad生命周期确无法输出内容，故对首页进行放行。有没有大佬能解释下?

**Comment by kosuke-zhang** [comment]
出现了同样的问题，打包成APP之后第一次安装进入，首页的tabs必先错误
