### ISSUE TITLE
我提交两bug吧。

### ISSUE THREAD

**Issue by tmzdy888** [umicro/uView#1047]
`我曾经在你们的群组：提过很多缺陷和bug.但被你们踢出来了，后来，我就很少使用你们的组件了。但最近我使用了你们的function下的js函数小工具，如果让我实现当然也可以，但有你们现成的，所以我就直接拿来使用，特此告诉下，感谢你们的贡献，我不记仇，也许只是你们少数管理员人品很差，不代表你们的整个团队。`

**我也像vant提过几个问题，他们团队很快就修复了，他们团队还是非常nice的**

下面是我目前已发现的几个问题：

> **第一个：timeFormat.js文件（修复兼容ios系统，ios第一次不能使用默认的2021-7-23 11:20:52赋值）：**
> `	// 如果为null,则格式化当前时间
> 	if (!dateTime) dateTime = Number(new Date());
> 	// 如果dateTime长度为10或者13，则为秒和毫秒的时间戳，如果超过13位，则为其他的时间格式
> 	if (dateTime.toString().length == 10) dateTime *= 1000;
> -----我的修复----开始---兼容ios系统
> 	if(typeof dateTime ==='string'){
> 		dateTime = dateTime.replace(/-/g,'/');
> 	}
> -----我的修复-----结束
> `

> 
> ### 第二个：getParent.js，其中的判断：parent.$options.name 建议改成：parent.$options?.name
> 因为如果我不赋值name，你的程序直接死掉了。

> 第三个：组件：u-row.vue
> `下方是你们的注释，我其实理解了你们的意思，但是：其实是可以解决的。
> .u-row {
> 		// 由于微信小程序编译后奇怪的页面结构，只能使用float布局实现，flex无法实现
> 		/* #ifndef MP-WEIXIN || MP-QQ || MP-TOUTIAO */
> 		@include vue-flex;
> 		/* #endif */
> 		flex-wrap: wrap;
> 	}` 
> 我现说下我的理解：
> 在h5端vue会把 template组件文件比如：`<u-row></u-row>`
> 替换成你们正常的结构体。
> 但在微信小程序中本身组件名称会占据一元素体很像`<div  inline-block>`，但又不像。
> 其实要像`H5`保持统一，只要在建组件的时时候多套一层view正常样式写在下一层即可解决。比如你们的row可以这样写：
> `
> <template>
>        <view class="u-row">
>           <view  :style="{
> 			alignItems: uAlignItem,
> 			justifyContent: uJustify
> 		}"
> 		@tap.stop.prevent="click"
> 	>
> 		<slot />
> 	</view>
>        </view>
> </template>
> `

以上是我近期发现的问题的。我没有看全你们的源码，如果后续有发现，会提出来。

**Comment by LiZhiCai1008** [comment]
假装没看到系列

**Comment by MunMunMiao** [comment]
几百年不更新了，早废弃了
