### ISSUE TITLE
如何根据注释生成文档？

### ISSUE THREAD

**Issue by CNMathon** [umicro/uView#1051]
Hi,
    我们发现代码中有不少已经注释了的代码，我们希望通过这些符合 jsdoc 规范的注释生成文档？我们应该如何做呢？

**Comment by tttao7** [comment]
为何要做这样的操作？官方文档是哪里不够好么？

**Comment by CNMathon** [comment]
@tttao7 是因为我们内部需要对 uView 进行二开，我们希望能够修改完代码后更新文档，以便团队其他成员使用最新的API。

**Comment by tttao7** [comment]
> @tttao7 是因为我们内部需要对 uView 进行二开，我们希望能够修改完代码后更新文档，以便团队其他成员使用最新的API。

等待我们开放uView官方文档吧。
