### ISSUE TITLE
支付宝小程序tabbar before-switch回调方法未执行

### ISSUE THREAD

**Issue by shishunyi** [umicro/uView#1088]
![image](https://user-images.githubusercontent.com/36780891/129824158-5fe9a950-9a33-4a94-81d4-039d911ece0e.png)

**Comment by shishunyi** [comment]
h5和微信小程序正常  就支付宝小程序未调用

**Comment by yatoku** [comment]
https://github.com/dcloudio/uni-app/issues/2273
