### ISSUE TITLE
使用u-checkbox-group警告提示

### ISSUE THREAD

**Issue by CrazyProgrammer12138** [umicro/uView#1094]
使用u-checkbox-group警告提示，注释了就没有了
VM2628 WAService.js:2 [Component] property received type-uncompatible value: expected <String> but get null value. Used empty string instead.
![image](https://user-images.githubusercontent.com/29749377/130312759-118e8048-b45e-4587-a237-bc5c8048e845.png)
求大神告知什么问题！

**Comment by ysneo** [comment]
同样 不知道啥问题。

**Comment by huzewei** [comment]
微信 2.18.0 以下的版本就不警告这个问题了。2.18.0+ 版本 v-model 定义的要在data 声明
