### ISSUE TITLE
u-dropdown 使用 v-if 控制 item 显示渲染异常问题

### ISSUE THREAD

**Issue by XeCtvi** [umicro/uView#1096]
``` 
<u-dropdown>
        <u-dropdown-item  v-if="!hasLocate || currentIndex == 1"/>
        <u-dropdown-item v-if="!hasLocate" />
</u-dropdown>
```

当 v-if 的值进行切换的时候（true 、false），对应的 `<u-dropdown-item>` 将会被重复渲染

![image](https://user-images.githubusercontent.com/10743176/130383893-67e97e51-a03d-4c2e-8d53-1359808ccb7e.png)

**Comment by yatoku** [comment]
你这个`if`的判断有问题吧 当`hasLocate`为`false`的时候就显示两个了
