### ISSUE TITLE
u-select点击白色区域 会出现事件击穿的问题  ios12必现

### ISSUE THREAD

**Issue by Alan055** [umicro/uView#1105]
使用u-select  点击白色区域会出现事件击穿的问题  ios必现

![WechatIMG413](https://user-images.githubusercontent.com/38103380/131316836-9108dd1f-e334-4d04-846b-2310cd04dd81.jpeg)
![WechatIMG414](https://user-images.githubusercontent.com/38103380/131316858-efa19aaa-4d1d-461b-84d1-4318643167fd.jpeg)
![WechatIMG412](https://user-images.githubusercontent.com/38103380/131316865-34a72ece-e88c-436d-8278-77e914d8f57d.jpeg)

**Comment by Alan055** [comment]
已收到，我会尽快查看的，谢谢（自动回复）

**Comment by Alan055** [comment]
我也没解决





------------------ 原始邮件 ------------------
发件人: bigCongee ***@***.***&gt;
发送时间: 2021年12月16日 17:15
收件人: umicro/uView ***@***.***&gt;
抄送: Alan ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[umicro/uView] u-select点击白色区域 会出现事件击穿的问题  ios12必现 (#1105)





 
请问怎么解决的这个问题 uview 1.x 在ios所有遮罩都会穿透必现的那种
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bigCongee** [comment]
那你的项目怎么上线呀,有其他方式代替吗

**Comment by Alan055** [comment]
上线后没管这个问题，唉太坑了





------------------ 原始邮件 ------------------
发件人: bigCongee ***@***.***&gt;
发送时间: 2021年12月16日 17:23
收件人: umicro/uView ***@***.***&gt;
抄送: Alan ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[umicro/uView] u-select点击白色区域 会出现事件击穿的问题  ios12必现 (#1105)





 
那你的项目怎么上线呀,有其他方式代替吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MuYuLPW** [comment]
给input和textarea设置disabled为true，设置监听，点击的时候再把disabled改为false，当失去焦点再改成true，可以完美解决这个问题

**Comment by Alan055** [comment]
已收到，我会尽快查看的，谢谢（自动回复）

**Comment by yatoku** [comment]
这个是因为`input`和`textarea`是原生组件导致的，与uview无关

**Comment by Alan055** [comment]
已收到，我会尽快查看的，谢谢（自动回复）
