### ISSUE TITLE
希望 尽快支持vue3版本

### ISSUE THREAD

**Issue by SngBlog** [umicro/uView#1106]
uniapp陆续开始支持vue3了
希望uview加油！

**Comment by xiaoyu-666** [comment]
> uniapp陆续开始支持vue3了
> 希望uview加油！

我看够呛， 最新版本更新日期是3月15号的，我看以后大概率会黄掉，没人管了

**Comment by 1622583480** [comment]
> > uniapp陆续开始支持vue3了
> > 希望uview加油！
> 
> 我看够呛， 最新版本更新日期是3月15号的，我看以后大概率会黄掉，没人管了
那完犊子了，vue3上来了，啥组件库都用不了

**Comment by xiaoyu-666** [comment]
> > > uniapp陆续开始支持vue3了
> > > 希望uview加油！
> > 
> > 
> > 我看够呛， 最新版本更新日期是3月15号的，我看以后大概率会黄掉，没人管了
> > 那完犊子了，vue3上来了，啥组件库都用不了

我新项目也在考虑用不用这个这个组件库了，我看了发版日期，我估计这个组件库是20年疫情爆发的时候一群程序员在家无聊的时候写的吧

**Comment by xiaoyu-666** [comment]
我准备打算自己边写边用，就看项目周期允许不

**Comment by 1622583480** [comment]
> > > > uniapp陆续开始支持vue3了
> > > > 希望uview加油！
> > > 
> > > 
> > > 我看够呛， 最新版本更新日期是3月15号的，我看以后大概率会黄掉，没人管了
> > > 那完犊子了，vue3上来了，啥组件库都用不了
> 
> 我新项目也在考虑用不用这个这个组件库了，我看了发版日期，我估计这个组件库是20年疫情爆发的时候一群程序员在家无聊的时候写的吧

我是新项目正好用到uniapp，想看看能不能整个什么组件库

**Comment by 1622583480** [comment]
> 我准备打算自己边写边用，就看项目周期允许不

我打算做项目的时候自己顺便写个组件库玩玩，一样不允许，我现在都开始找其他原生app的方案了

**Comment by xiaoyu-666** [comment]
> > 我准备打算自己边写边用，就看项目周期允许不
> 
> 我打算做项目的时候自己顺便写个组件库玩玩，一样不允许，我现在都开始找其他原生app的方案了

![微信图片_20210831172538](https://user-images.githubusercontent.com/27267958/131478174-b11b7fe5-ae79-4541-a0c6-29bb6ad56507.png)
看看这张图，除了没用过的其他的都用了

**Comment by 1622583480** [comment]
> > > 我准备打算自己边写边用，就看项目周期允许不
> > 
> > 
> > 我打算做项目的时候自己顺便写个组件库玩玩，一样不允许，我现在都开始找其他原生app的方案了
> 
> ![微信图片_20210831172538](https://user-images.githubusercontent.com/27267958/131478174-b11b7fe5-ae79-4541-a0c6-29bb6ad56507.png)
> 看看这张图，除了没用过的其他的都用了

谢谢大佬，我抽空看看其他组件库

**Comment by boot-vue** [comment]
😭   还是得靠自己

**Comment by 1622583480** [comment]
> 😭 还是得靠自己

总之vue3版本几乎无组件库可以用
