### ISSUE TITLE
u-upload可以支持上传视频吗？

### ISSUE THREAD

**Issue by qzsiniong** [umicro/uView#1112]
目前u-upload只可以上传图片，是否可以支持下上传视频呢。

**Comment by nadirvishun** [comment]
不可以，只支持图片。
- 可以直接用uniapp自带的api来自己实现：[uni.uploadFile](https://uniapp.dcloud.io/api/request/network-file?id=uploadfile)
- 或者是用uni-ui里的[uni-file-picker 文件选择上传](https://ext.dcloud.net.cn/plugin?id=4079)
