### ISSUE TITLE
u-select第二次弹出选择之后，如果没有给default-value，上次选中数据丢失的问题

### ISSUE THREAD

**Issue by jason-zhcn** [umicro/uView#1116]
1.  选择对应的数据之后，正常保存之后。
2.  重新弹出选择框，选中的数据不变，直接点击确定后，选中的index跳到了索引 0 的位置。

**Comment by jason-zhcn** [comment]
![image](https://user-images.githubusercontent.com/89151465/133216209-a084e9f6-8d47-4f67-a8b2-b73779dec345.png)
初始化判断与change判断不一致，如果extra为数字0，则无法被正确赋值。

**Comment by wz930206** [comment]
按照目前写的逻辑，需要自己把下标算出来，传过去，如下
![image](https://user-images.githubusercontent.com/37261842/133230465-3b224d2f-23a8-4be7-9f06-769450d0dea9.png)
u-select 中也注释了
![image](https://user-images.githubusercontent.com/37261842/133230652-3bb093b5-1e8f-474c-82b3-bc1671562c0e.png)

**Comment by Mrchen128** [comment]
我已经设置了默认值0，为什么打开显示的是我上次选择的那一列

**Comment by Mrchen128** [comment]
我已经设置了默认值0，为什么打开显示的是我上次选择的那一行
![1631936971(1)](https://user-images.githubusercontent.com/43802788/133871643-d4dcd83c-2916-4038-b8e2-19db70d601ec.jpg)

**Comment by Mrchen128** [comment]
下面的选择器默认值没有按照预期设置为第一个

**Comment by aimeiyijia** [comment]
> 下面的选择器默认值没有按照预期设置为第一个

你解决了嘛？

**Comment by HNyyj** [comment]
请问解决了吗，我是通过extra参数，直接设置default-value，但是真的没必要，为什么不能直接定位或者恢复

**Comment by yatoku** [comment]
#1173
