### ISSUE TITLE
u-popup能不能不用scroll-view嵌套，导致样式问题

### ISSUE THREAD

**Issue by fengcanluoye** [umicro/uView#1121]
![输入图片说明](https://images.gitee.com/uploads/images/2021/0916/150943_6bddf7ac_2128683.png "D974F20E-29EB-4c94-8070-E68B58ED0056.png")
![输入图片说明](https://images.gitee.com/uploads/images/2021/0916/150952_2f08773f_2128683.png "微信截图_20210916150726.png")

如图，这种效果，用scroll-view嵌套，根本无法使用样式穿透修改

**Comment by Hsensor** [comment]
自己重写一个u-popup组件吧，我就是这样干的
我的设计是popup内容外面一个close按钮

**Comment by Hsensor** [comment]
如果直接使用u-popup多数情况下scrollview，外面需要再次嵌套scrollview （更鸡肋）

**Comment by fengcanluoye** [comment]
> 自己重写一个u-popup组件吧，我就是这样干的
> 我的设计是popup内容外面一个close按钮

嗯，我把它的源代码拿出了改了下写了个新组件，scroll-view换成view
