### ISSUE TITLE
upload组件，打开默认摄像头问题

### ISSUE THREAD

**Issue by xu-Aurora** [umicro/uView#1131]
添加属性source-type为['camera']时，默认是打开手机的的后置摄像头，有办法做到默认打开的是手机的前置摄像头嘛？

**Comment by yatoku** [comment]
没有。`upload`组件选择文件使用的是`uniapp`的`uni.chooseImage`，如果想要默认打开摄像头的话，请自行修改源码使用[plus.camera](https://www.html5plus.org/doc/zh_cn/camera.html)进行替换
