### ISSUE TITLE
使用Vue3模式的main.js语法，无法正常导入uView UI组件库

### ISSUE THREAD

**Issue by BruceAn1978** [umicro/uView#1146]
main.js代码：
```
import App from './App'
import uView from './uview-ui'
import {createSSRApp} from 'vue'

export function createApp()
{
  const app = createSSRApp(App)
  app.use(uView)

  return {app}
}
```

运行后控制台报错：

> Uncaught SyntaxError: The requested module '/uview-ui/libs/mixin/mixin.js' does not provide an export named 'default'

**Comment by mhxy13867806343** [comment]
这个ui库，现在只支持vue2的

**Comment by BruceAn1978** [comment]
谢谢！

有vue3版本升级的计划或者时间点没有？

**Comment by yatoku** [comment]
> 谢谢！
> 
> 有vue3版本升级的计划或者时间点没有？

暂时没有，可能需要等uniapp vue3稳定以后才会考虑
