### ISSUE TITLE
swiper+waterfall只有一条数据的问题

### ISSUE THREAD

**Issue by luohuam** [umicro/uView#1148]
waterfall只有一条数据时，来回切换swiper，每切换一次都会复制那一条数据重复显示
![image](https://user-images.githubusercontent.com/23612746/137842039-eb32bad3-06fd-4af7-bac1-c21286f7e503.png)
![image](https://user-images.githubusercontent.com/23612746/137842110-83c7a079-dda5-40d4-8321-d0a1e34dc595.png)

**Comment by PachVerb** [comment]
#

> waterfall只有一条数据时，来回切换swiper，每切换一次都会复制那一条数据重复显示 ![image](https://user-images.githubusercontent.com/23612746/137842039-eb32bad3-06fd-4af7-bac1-c21286f7e503.png) ![image](https://user-images.githubusercontent.com/23612746/137842110-83c7a079-dda5-40d4-8321-d0a1e34dc595.png)

遇到同样的问题。请问，你那边解决了吗

**Comment by yatoku** [comment]
切换显示时，先调用一下组件内部的`clear`方法。
