### ISSUE TITLE
version: 1.8.4 u-form组件props: border-bottom样式失效。

### ISSUE THREAD

**Issue by psrheartache** [umicro/uView#1150]
border-bottom默认开启，
查询 html发现dom有class=“u-border-bottom”，
调试发现无法出现表单底部下划线。
遂补充样式如下：
.u-border-bottom{
position: relative;
}
.u-border-bottom:after{
content: " ";
position: absolute;
left: 0;
top: 0;
pointer-events: none;
box-sizing: border-box;
-webkit-transform-origin: 0 0;
transform-origin: 0 0;
width: 199.8%;
height: 199.7%;
-webkit-transform: scale(.5);
transform: scale(.5);
border-bottom: 2px solid #e4e7ed;
z-index: 2;
}
成功显示下划线。

**Comment by yatoku** [comment]
这个是全局样式。可能是你没有引入全局样式的scss
