### ISSUE TITLE
uview http 请求 loading的问题

### ISSUE THREAD

**Issue by wangyuan0217** [umicro/uView#1157]
场景：比如一个页面需要同时调用多个接口，有些场景的接口需要loading，有些不需要loading。怎么动态控制对应的接口是否需要loading呢。或者说同一个接口第一次需要loading，之后就不需要loading（加载更多的时候）。谢谢。

**Comment by wangyuan0217** [comment]
这么靠前的框架，这么多问题， Issue目前为止763open 268closed的

**Comment by huzewei** [comment]
自己封装一个不就行了。我现在就是自己封装的。

**Comment by stringworld** [comment]
> 场景：比如一个页面需要同时调用多个接口，有些场景的接口需要loading，有些不需要loading。怎么动态控制对应的接口是否需要loading呢。或者说同一个接口第一次需要loading，之后就不需要loading（加载更多的时候）。谢谢。

这边是加了个参数，在请求拦截器里面判断loading是否要显示，默认都显示loading，不需要的时候传，isShowLodaing:false
![image](https://user-images.githubusercontent.com/9764134/141410266-a581905f-a01f-4c2c-8f86-c230c6a5a3d8.png)

**Comment by yatoku** [comment]
可以在请求前使用`$u.http.setConfig()`设置是否显示`loading`
