### ISSUE TITLE
u-card组件 Cannot read property 'foot' of undefined

### ISSUE THREAD

**Issue by loanon** [umicro/uView#1159]
版本1.8.4 

u-card组件报如下错误

```bash
vendor.js:8187 TypeError: Cannot read property 'foot' of undefined
    at Proxy.render (u-card.js:113)
    at VueComponent.Vue._render (vendor.js:5944)
    at VueComponent.updateComponent (vendor.js:8071)
    at Watcher.get (vendor.js:6804)
    at new Watcher (vendor.js:6791)
    at mountComponent$1 (vendor.js:8077)
    at VueComponent.Vue.$mount (vendor.js:8394)
    at vendor.js:1955
    at Array.forEach (<anonymous>)
    at initChildVues (vendor.js:1940)
```

看代码应该是这里报错，请问有人知道怎么解决吗，我不是专业前端，还请知道的指点一下。

```js
<view
	v-if="showFoot"
	class="u-card__foot"
		@tap="footClick"
	:style="[{padding: $slots.foot ? padding + 'rpx' : 0}, footStyle]" // $slots 是 undefined，源码中63行
	:class="{
		'u-border-top': footBorderTop
	}"
>
	<slot name="foot" />
</view>
```

**Comment by loanon** [comment]
环境是支付宝小程序和微信小程序，web端好像没这个问题

**Comment by loanon** [comment]
找到原因了。
首先这个问题应该是支付宝小程序下才会出现的，原因是uniapp在支付宝环境下，$slots 是 undefined的问题，官方网站有人提问了，解决方式是在支付宝小程序配置文件中开启component2。

**Comment by lorange** [comment]
> 

我项目之前还没这个问题，更新了一下HbuilderX后出现了此问题，按照您说的component2也开启了，但是还是报这个错误。我编译到支付宝小程序运行，功能不受影响，但u-card的样式失效了。

**Comment by lorange** [comment]
> > 
> 
> 我项目之前还没这个问题，更新了一下HbuilderX后出现了此问题，按照您说的component2也开启了，但是还是报这个错误。我编译到支付宝小程序运行，功能不受影响，但u-card的样式失效了。

并且发现项目中u-view的其他组件也报了类似错误，比如 u-cell-item。我现在跑uview1.8.3版本的官方示例也会报同样的错误

**Comment by loanon** [comment]
个人认为是你开启component2的方式有问题

需要看你项目实际结构决定，比如我的项目是支付宝的多端工程，里面有支付宝的配置文件和uni-app的配置文件，在uni-app的配置文件中配置component2并不生效，需要直接配置支付宝的配置文件。

所以看一下你项目根目录是否有mini.project.json，如果有，请直接在这个文件中配置。

**Comment by jscgq** [comment]
同样遇到此问题，uniapp以及mini.project.json都配置开启了component2，依旧出现。

**Comment by jscgq** [comment]
不要采用小程序基础库2.0构建， 无此问题

**Comment by wcccccj** [comment]
这个问题还没解决吧，不采用小程序基础库2.0构建不是不能真机调试吗？
