### ISSUE TITLE
建议去掉js模块

### ISSUE THREAD

**Issue by HZ-ZY** [umicro/uView#1165]
建议去掉js模块，没必要，小程序占用大量的体积，同时建议加入自定义主题，更加规范些。地址信息json类数据建议放在线上，放本地不是一般大。。

**Comment by LDXu** [comment]
可以参考有赞，提供了一个地址json是另一个npm库

**Comment by yatoku** [comment]
uview1.0中应该不会去掉了,但是uview2中已经去掉了地址的选择
