### ISSUE TITLE
2.0，目前支持vue3吗

### ISSUE THREAD

**Issue by 824201769** [umicro/uView#1176]

**Comment by sail-sail** [comment]
尝试了一下, 疑似不支持vue3

**Comment by yatoku** [comment]
不支持

**Comment by sail-sail** [comment]
现在问题不大了, 我已经用 @vue/composition-api 跟 unplugin-vue2-script-setup 改造一下, 来实现了 vue3 的 setup 语法+ 组合式API 的方式了, 虽然是vue2 但模拟了vue3的语法

**Comment by BruceAn1978** [comment]
> 现在问题不大了, 我已经用 @vue/composition-api 跟 unplugin-vue2-script-setup 改造一下, 来实现了 vue3 的 setup 语法+ 组合式API 的方式了, 虽然是vue2 但模拟了vue3的语法

如何模拟的，我也是Vue3语法报错了。
