### ISSUE TITLE
input bug

### ISSUE THREAD

**Issue by itoic** [umicro/uView#1177]
![PMTB0H25`W6T03@KSLKWUD5](https://user-images.githubusercontent.com/25840453/141944074-9a91ec3e-7e7e-416e-b680-069ea392a64f.png)

![118@50N$AJE7OL34(GEDE%V](https://user-images.githubusercontent.com/25840453/141944107-6e76c451-2515-459d-ad2a-9f540e30ef06.png)
少了一个k字母

**Comment by yatoku** [comment]
已经修复了。虽然但是，这个是uview2的。你发到uview1来了- -
