### ISSUE TITLE
uVIew1.0，HBuilderX直接导入示例项目，代码无提示

### ISSUE THREAD

**Issue by abc101014** [umicro/uView#1189]
### 版本
1.8.2

### 转载链接
[ext.dcloud.net.cn/plugin](https://ext.dcloud.net.cn/plugin?id=6682)

### 重现步骤
uVIew1.0，HBuilderX直接导入示例项目，无任何修改，代码无提示。 导入链接：https://ext.dcloud.net.cn/plugin?id=6682
HBuilderX版本：3.2.16.20211122
系统：macOS 11.6.1

### 期望的结果是什么？
有代码提示

### 实际的结果是什么？
没有提示

**Comment by yatoku** [comment]
在HBX中重新构建项目索引

**Comment by abc101014** [comment]
> 

谢谢！
