### ISSUE TITLE
u-modal content 内容中的\n 不换行

### ISSUE THREAD

**Issue by wangyuan0217** [umicro/uView#1192]
### 版本
1.8.2

u-modal content 内容中的\n 不换行

**Comment by yatoku** [comment]
`html`中的`\n`才会换行，`u-modal`组件的`content`属性是直接放在标签中的

**Comment by wangyuan0217** [comment]
那要怎么实现content内容 换行啊

**Comment by wangyuan0217** [comment]
> `html`中的`\n`才会换行，`u-modal`组件的`content`属性是直接放在标签中的

那要怎么实现content内容 换行啊
