### ISSUE TITLE
u-switch组件v-model绑定非布尔值时报错

### ISSUE THREAD

**Issue by ruandk** [umicro/uView#1196]
### 版本
1.8.2

### 重现步骤
```
<u-switch v-model="isDefault" :active-value='1' :inactive-value='0'></u-switch>

data(){
  return {
    isDefault: 0
  }
}
```

### 期望的结果是什么？
v-model可绑定一个非布尔值，既然active-value和inactive-value支持Boolean | Number | String，value理应也如此

### 实际的结果是什么？
v-model绑定非布尔值时报错

---
服务端给到数据为非布尔值，u-switch也支持指定active-value和inactive-value，并且支持多种类型，value不应只支持布尔值，应避免带来不必要的类型转换

**Comment by yatoku** [comment]
`v-model`需要绑定的就是布尔值，设置了`acttive-value`和`inactive-value`，只是可以在触发`change`事件时可以接收。

**Comment by ruandk** [comment]
@yatoku  uView2.0已支持，为啥uView1.8不可以同步支持？老项目换成uView2.0改动大

**Comment by malinops** [comment]
> [@yatoku](https://github.com/yatoku) uView2.0已支持，为啥uView1.8不可以同步支持？老项目换成uView2.0改动大
uview 1版本的用我改的

<template>
	<view class="u-switch" :class="[valueCom == true ? 'u-switch--on' : '', disabled ? 'u-switch--disabled' : '']"
		@tap="onClick" :style="[switchStyle]">
		<view class="u-switch__node node-class" :style="{
				width: $u.addUnit(size),
				height: $u.addUnit(size)
			}">
			<u-loading :show="loading" class="u-switch__loading" :size="size * 0.6" :color="loadingColor" />
		</view>
	</view>
</template>

<script>
	/**
	 * switch 开关选择器
	 * @description 选择开关一般用于只有两个选择，且只能选其一的场景。
	 * @tutorial https://www.uviewui.com/components/switch.html
	 * @property {Boolean} loading 是否处于加载中（默认false）
	 * @property {Boolean} disabled 是否禁用（默认false）
	 * @property {String Number} size 开关尺寸，单位rpx（默认50）
	 * @property {String} active-color 打开时的背景色（默认#2979ff）
	 * @property {Boolean} inactive-color 关闭时的背景色（默认#ffffff）
	 * @property {Boolean | Number | String} active-value 打开选择器时通过change事件发出的值（默认true）
	 * @property {Boolean | Number | String} inactive-value 关闭选择器时通过change事件发出的值（默认false）
	 * @event {Function} change 在switch打开或关闭时触发
	 * @example <u-switch v-model="checked" active-color="red" inactive-color="#eee"></u-switch>
	 */
	export default {
		name: "u-switch",
		emits: ["update:modelValue", "input", "change"],
		props: {
			// 通过v-model双向绑定的值
			value: {
				type: [Number, String, Boolean],
				default: false
			},
			modelValue: {
				type: [Number, String, Boolean],
				default: false
			},
			// 是否为加载中状态
			loading: {
				type: Boolean,
				default: false
			},
			// 是否为禁用装填
			disabled: {
				type: Boolean,
				default: false
			},
			// 开关尺寸，单位rpx
			size: {
				type: [Number, String],
				default: 50
			},
			// 打开时的背景颜色
			activeColor: {
				type: String,
				default: "#2979ff"
			},
			// 关闭时的背景颜色
			inactiveColor: {
				type: String,
				default: "#ffffff"
			},
			// 是否使手机发生短促震动，目前只在iOS的微信小程序有效(2020-05-06)
			vibrateShort: {
				type: Boolean,
				default: false
			},
			// 打开选择器时的值
			activeValue: {
				type: [Number, String, Boolean],
				default: true
			},
			// 关闭选择器时的值
			inactiveValue: {
				type: [Number, String, Boolean],
				default: false
			}
		},
		data() {
			return {};
		},
		computed: {
			valueCom() {
				// #ifndef VUE3
				return this.value;
				// #endif

				// #ifdef VUE3
				return this.modelValue;
				// #endif
			},
			
			    // ✅ 新增：判断当前是否为“打开”状态
			    isChecked() {
			        return this.valueCom === this.activeValue;
			    },
			
			    // 使用 isChecked 来决定背景色
			    switchStyle() {
			        let style = {};
			        style.fontSize = this.size + "rpx";
			        style.backgroundColor = this.isChecked ? this.activeColor : this.inactiveColor;
			        return style;
			    },
			
			    loadingColor() {
			        return this.isChecked ? this.activeColor : null;
			    }
		},
		methods: {
			onClick() {
				if (!this.disabled && !this.loading) {
					// 使手机产生短促震动，微信小程序有效，APP(HX 2.6.8)和H5无效
					if (this.vibrateShort) uni.vibrateShort();
					 const newValue = this.isChecked ? this.inactiveValue : this.activeValue;
					
					        this.$emit("input", newValue);
					        this.$emit("update:modelValue", newValue);
					
					        // 注意：change 事件也要传实际值（activeValue/inactiveValue）
					        this.$nextTick(() => {
					            this.$emit("change", newValue);
					        });
				}
			}
		}
	};
</script>

<style lang="scss" scoped>
	@import "../../libs/css/style.components.scss";

	.u-switch {
		position: relative;
		/* #ifndef APP-NVUE */
		display: inline-block;
		/* #endif */
		box-sizing: initial;
		width: 2em;
		height: 1em;
		background-color: #fff;
		border: 1px solid rgba(0, 0, 0, 0.1);
		border-radius: 1em;
		transition: background-color 0.3s;
		font-size: 50rpx;
	}

	.u-switch__node {
		@include vue-flex;
		align-items: center;
		justify-content: center;
		position: absolute;
		top: 0;
		left: 0;
		border-radius: 100%;
		z-index: 1;
		background-color: #fff;
		background-color: #fff;
		box-shadow: 0 3px 1px 0 rgba(0, 0, 0, 0.05), 0 2px 2px 0 rgba(0, 0, 0, 0.1),
			0 3px 3px 0 rgba(0, 0, 0, 0.05);
		box-shadow: 0 3px 1px 0 rgba(0, 0, 0, 0.05), 0 2px 2px 0 rgba(0, 0, 0, 0.1),
			0 3px 3px 0 rgba(0, 0, 0, 0.05);
		transition: transform 0.3s cubic-bezier(0.3, 1.05, 0.4, 1.05);
		transition: transform 0.3s cubic-bezier(0.3, 1.05, 0.4, 1.05),
			-webkit-transform 0.3s cubic-bezier(0.3, 1.05, 0.4, 1.05);
		transition: transform cubic-bezier(0.3, 1.05, 0.4, 1.05);
		transition: transform 0.3s cubic-bezier(0.3, 1.05, 0.4, 1.05);
	}

	.u-switch__loading {
		@include vue-flex;
		align-items: center;
		justify-content: center;
	}

	.u-switch--on {
		background-color: #1989fa;
	}

	.u-switch--on .u-switch__node {
		transform: translateX(100%);
	}

	.u-switch--disabled {
		opacity: 0.4;
	}
</style>
