### ISSUE TITLE
从插件市场导入插件，安装路径有问题

### ISSUE THREAD

**Issue by Xyuan-abs** [umicro/uView#1203]
### 版本
1.8.5

### 复现链接
该bug无法提供复现链接
![image](https://user-images.githubusercontent.com/64180387/148516590-0a330932-d7f5-4339-acdc-c345208ef6c1.png)

### 重现步骤
直接从插件市场安装uview1

### 期望的结果是什么？
项目根目录下生成一个uview-ui文件夹，里面存放插件相关文件

### 实际的结果是什么？
插件相关文件直接生成在项目根目录下

**Comment by yatoku** [comment]
这个是dcloud的原因，修改版本以后不能直接生成在项目根目录下了。
