### ISSUE TITLE
请问框架内置语言 如何多语言切换

### ISSUE THREAD

**Issue by y-takeon** [umicro/uView#1205]
### 版本
1.8.5

### 转载链接
[localhost/h5/](http://localhost:8080/h5/#/pages/storeManagement/outsourceCheck/index)

### 重现步骤
点击删除照片时提示语显示英语或其他语言

### 期望的结果是什么？
内置语言切换

### 实际的结果是什么？
无法切换

**Comment by yatoku** [comment]
目前组件没有提供多语言功能，如果需要使用的话，可以对特定版本组件进行多语言配置

**Comment by y-takeon** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umicro/uView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umicro/uView] 请问框架内置语言 如何多语言切换 (Issue #1205)





 
目前组件没有提供多语言功能，如果需要使用的话，可以对特定版本组件进行多语言配置
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
