### ISSUE TITLE
该如何中断请求

### ISSUE THREAD

**Issue by Qiuyan06** [umicro/uView#1207]
### 这个功能解决了什么问题？
请求发出去之后，切换选项卡需要中断请求。

### 你期望的 API 是怎样的？
希望暴露中断请求的方法

**Comment by Qiuyan06** [comment]
想要类似这样的效果
![image](https://user-images.githubusercontent.com/68538063/150483837-58d16f9e-ef0c-48f7-8825-64f4f77d500d.png)

**Comment by yatoku** [comment]
可以在请求拦截中断，如果发起请求后，目前没有

**Comment by Qiuyan06** [comment]
想要发起请求后中断请求

**Comment by yatoku** [comment]
uview1中没有这个功能
