### ISSUE TITLE
关于Dropdown 下拉菜单使用定位后 遮罩会遮盖其余页面导致其余部分无法点击和滚动(含解决建议)

### ISSUE THREAD

**Issue by 1720360649** [umicro/uView#1212]
### 版本
1.8.5

### 转载链接
[localhost/](http://localhost:8081/#/pages/index/index)

### 重现步骤
引入 Dropdown 后设置 包裹一层view ，给其父标签设置position: fixed;z-index: 999; 
此时会发现页面其余部分被 .u-dropdown__content 及 .u-dropdown__content__mask 元素遮挡

### 期望的结果是什么？
下拉菜单未展开时其余部分可点击及滚动

### 实际的结果是什么？
无法点击及滚动

---
解决建议，在下拉菜单默认状态下（close状态） 将 .u-dropdown__content 元素高度设置为0 ，open状态下才给予其高度。
此解决方法不会对目前组件结构及性能造成影响，仅需在现有修改index及opacity的同时一起修改高度即可

**Comment by 17797776321** [comment]
这个问题时真的傻逼。。。我业务代码啥都写完了，诶，怎么滚动不了！然后 发现有个透明的mask在挡住！！！单独给样式加个pointer-events: none都不行！最后只能放弃这个组件！！

**Comment by xintianyou** [comment]
@17797776321 
https://github.com/umicro/uView/issues/1239看这个
