### ISSUE TITLE
app真机调试访问分包页面报错

### ISSUE THREAD

**Issue by sharkcheung** [umicro/uView#1218]
### 版本
1.8.5

### 转载链接
[images.gitee.com](https://images.gitee.com/uploads/images/2022/0323/162933_7ec17cc7_1797285.png)

### 重现步骤
app进行真机调试时，访问分包页面就会出现此bug

### 期望的结果是什么？
能正常访问

### 实际的结果是什么？
报错，无法访问

**Comment by yatoku** [comment]
请不要提交这种意义不明的issues
