### ISSUE TITLE
如果服务端返回的不是200状态，插件内部弹出model提示能否提供开关供使用者选择是否弹出？

### ISSUE THREAD

**Issue by Laiyit** [umicro/uView#122]
这个地方能否由使用者选择是否弹框：

`// 不返回原始数据的情况下，服务器状态码不为200，modal弹框提示
						if(response.errMsg) {
							uni.showModal({
								title: response.errMsg
							});
						}`

**Comment by tttao7** [comment]
此问题我们已收到，感谢您的反馈
