### ISSUE TITLE
真机调试app的时候，进入分包页访问空白，且报错 [JS Framework] Failed to execute the callback function: TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by sharkcheung** [umicro/uView#1220]
### 版本
1.8.5

### 转载链接
[http://localhost/](http://localhost)

### 重现步骤
打开真机调试，点分包页面进去

### 期望的结果是什么？
分包页面显示正常

### 实际的结果是什么？
分包页面空白，并报错

**Comment by yatoku** [comment]
缺少报错信息描述
