### ISSUE TITLE
微信小程序ios端 Mask点击事件会穿透Input 安卓没有该bug

### ISSUE THREAD

**Issue by SoonIter** [umicro/uView#1226]
### 版本
1.8.6

### 转载链接
[http://localhost:8080/](http://localhost:8080)

### 重现步骤
![2at8g.png](https://s1.328888.xyz/2022/04/23/2at8g.png)
![2aDwZ.jpg](https://s1.328888.xyz/2022/04/23/2aDwZ.jpg)
![2adBC.png](https://s1.328888.xyz/2022/04/23/2adBC.png)
![2a5I1.png](https://s1.328888.xyz/2022/04/23/2a5I1.png)
![2aWvt.jpg](https://s1.328888.xyz/2022/04/23/2aWvt.jpg)
先点开一个带mask的组件（select calendar这些），然后点击白色部分（非mask遮罩部分），会触发input框

### 期望的结果是什么？
不会隔着层数触发input

### 实际的结果是什么？
触发了input

**Comment by yatoku** [comment]
打开`mask`后，可以先把`input`的`disable`设置为`true`。就不会遇到这个问题
