### ISSUE TITLE
支付宝下 会出现没有$slots 导致$slots.XXX异常报错的问题

### ISSUE THREAD

**Issue by thckbuibuibui** [umicro/uView#1229]
### 版本
1.8.6

### 转载链接
[ext.dcloud.net.cn/plugin](https://ext.dcloud.net.cn/plugin?id=6682)

### 重现步骤
支付宝下 会出现没有$slots 导致$slots.XXX异常报错的问题 项目示例直接运行就会出现这个异常

### 期望的结果是什么？
不报错

### 实际的结果是什么？
报错

---
如 v-if="$slots.label" 改成 v-if="$slots && $slots.label"

**Comment by yatoku** [comment]
#1159
