### ISSUE TITLE
u-form-item在小程序无法进行验证

### ISSUE THREAD

**Issue by 956632862** [umicro/uView#1230]
### 版本
1.8.5

### 转载链接
[xn--bug-x28doa2596aqocv12e.com](https://有bug不敢上线.com)

### 重现步骤
新建一个表单，直接设置自定义规则，在h5可以正常校验，在小程序不行，校验结果是false

### 期望的结果是什么？
你猜

### 实际的结果是什么？
你猜我为什么提bug

---
表单页面

**Comment by 956632862** [comment]
真服了这个提bug的页面了，怎么你们公司都不需要本地测试就敢上线嘛
还有那个加群的，一个空白的问题，官方文档都找不到的加群答案

**Comment by yatoku** [comment]
uview不是一个公司
