### ISSUE TITLE
u-dropdown-item 新增 active 类名，以支持自定义高亮时的样式

### ISSUE THREAD

**Issue by RJM1996** [umicro/uView#1238]
### 这个功能解决了什么问题？
u-dropdown-item 目前使用行内样式实现高亮的样式，导致不能自定义高亮的样式
如图：
![image](https://user-images.githubusercontent.com/33800707/170670945-38999fe0-24f4-43f1-990c-a245534f6f19.png)

### 你期望的 API 是怎样的？
把需要高亮的元素加一个 active 类名，用户可以重写类的样式来自定义高亮的样式

**Comment by yatoku** [comment]
可以`deep`
