### ISSUE TITLE
u-dropdown__content 高度未根据 active 状态变化，导致下面的元素无法点击

### ISSUE THREAD

**Issue by RJM1996** [umicro/uView#1239]
### 版本
1.8.6

### 转载链接
[http://192.168.0.101:8080/]( http://192.168.0.101:8080/)

### 重现步骤
u-dropdown 使用 fixed 定位

### 期望的结果是什么？
下拉菜单未展开时，u-dropdown__content 高度置为0

### 实际的结果是什么？
下拉菜单未展开时，u-dropdown__content 高度不为0，导致下面的元素不能点击

### 解决建议
<img width="583" alt="image" src="https://user-images.githubusercontent.com/33800707/171551023-13aa2510-b71e-4891-8ad2-187c011a924e.png">

**Comment by RJM1996** [comment]
分享一种不入侵源码的解决方法
在 open 和 close 事件触发时，动态修改 u-dropdown 组件的 contentHeight 属性即可
<img width="640" alt="image" src="https://user-images.githubusercontent.com/33800707/171551139-676127db-0360-4ef2-816b-57c9bbf1bb93.png">

**Comment by xintianyou** [comment]
干得漂亮

**Comment by xintianyou** [comment]
用这个方法，在真机上刚进入页面时还是会有一层覆盖的，要点击一下屏幕才消失

**Comment by xintianyou** [comment]
@xintianyou mounted延时10ms，真机上解决了
