### ISSUE TITLE
u-picker组件中，希望补充一下广东省深圳市的光明区!

### ISSUE THREAD

**Issue by Maxbsy** [umicro/uView#1247]
### 版本
1.8.6

### 转载链接
[gitee.com](https://gitee.com/umicro/uView/blob/master/uview-ui/libs/util/city.js)

### 重现步骤
u-picker组件中，希望补充一下广东省深圳市的光明区!现阶段我是拷贝一个组件，自行添加的。但是想到其他使用1.x版本的也会有这样的问题。

### 期望的结果是什么？
补充城市数据

### 实际的结果是什么？
缺少一个城市数据

**Comment by yatoku** [comment]
这个要自己修改的，没法保证省市区数据是最新的
