### ISSUE TITLE
u-upload 拍照点击无反应,可以选择本地照片

### ISSUE THREAD

**Issue by git-chenjiqing** [umicro/uView#1261]
### 版本
1.8.7

### 重现步骤
u-upload 拍照点击无反应,可以选择本地照片

### 期望的结果是什么？
u-upload 可以拍照也可以选择本地照片

### 实际的结果是什么？
u-upload 拍照点击无反应,可以选择本地照片

---
产品分类： uniapp/App
HBuilderX类型： 正式
HBuilderX版本号：3.4.18
手机系统： Android
手机系统版本号： Android 10
手机厂商： 华为手机
页面类型： vue
编译模式：本地资源文件：
打包方式：Android离线打包
离线项目创建方式： HBuilderX
Android SDK Build-Tools33

**Comment by yatoku** [comment]
你可以尝试真机调试看看
