### ISSUE TITLE
toast组件可否优化一下样式,文本内容过长一行显示不开

### ISSUE THREAD

**Issue by YongHangPu** [umicro/uView#137]
![image](https://user-images.githubusercontent.com/33919488/84556535-07549d80-ad56-11ea-92ee-a037c42487a6.png)

**Comment by tttao7** [comment]
您可以使用deep进行样式修改 由于需求各不相同 请谅解

**Comment by Corgis** [comment]
不用scope 然后加deep就可以改这个样式了吧
