### ISSUE TITLE
u-upload能不能直接返回file，有些场景其实是需要自定义上传请求的

### ISSUE THREAD

**Issue by GhostBoys** [umicro/uView#249]
u-upload能不能直接返回file算了，有些场景其实是需要自定义上传请求的，组件传的是直接传的file格式 而后台又要base64格式的

**Comment by Deadpool957** [comment]
这个问题解决了吗

**Comment by yaojin2070** [comment]
解决了吗, 有的话踢我一下

**Comment by TasonIV** [comment]
同问，要是能直接返回file就好了。题主的问题可通过uni.getFileSystemManager().readFile()将file转换成base64
![图片](https://user-images.githubusercontent.com/46587200/125012027-11051d80-e09c-11eb-81da-063530bd4013.png)

**Comment by yatoku** [comment]
uniapp中只有`H5`环境上传文件才会返回`file`，别的环境下是没有`file`
