### ISSUE TITLE
u-select, u-picker 弹出框会半透明显示u-input的内容

### ISSUE THREAD

**Issue by muziling** [umicro/uView#322]
比如页面里有两个组件，一个 u-select, 一个 u-input，u-input 类型为textarea
当  u-input 里随便输入一些内容，再去点击 u-select， u-select 弹出框会半透明显示u-input 输入的内容，u-input 不为textarea 时又是正常的（不会半透明显示u-input内容）

**Comment by tttao7** [comment]
此问题为原生组件问题，若为textarea，弹窗时请隐藏输入框。
