### ISSUE TITLE
在微信小程序的线上版本 Source Map 文件中出现了_vm.handleInput is not a function

### ISSUE THREAD

**Issue by chenjiecloud** [umicro/uView#350]
<img width="1043" alt="WX20200817-143930@2x" src="https://user-images.githubusercontent.com/31178795/90364909-8ab4a700-e097-11ea-9766-9a3adb2fa25b.png">
这个方法在项目中是没有使用过的，查看uview源码为u-input组件中使用的方法，望提供解决方法

**Comment by chenjiecloud** [comment]
@wlxuqu

**Comment by chenjiecloud** [comment]
还有一个onInput
<img width="979" alt="WX20200818-144708@2x" src="https://user-images.githubusercontent.com/31178795/90479758-c156f400-e161-11ea-80d9-2af5210616cf.png">

**Comment by chenjiecloud** [comment]
也只是用了u-field的组件，Source Map 文件给到的信息太少，无法排查，我在观察下

**Comment by chenjiecloud** [comment]
在微信小程序中，经过测试，这个是微信的一个bug，主要是在手写输入中文的时候，input的最后一个值有可能获取不到，而且会报_vm.handleInput is not a function 和 _vm.onInput is not a function 的报错，看社区中有使用blur来处理，不知道是否可行，待验证

**Comment by ZHD-East** [comment]
我在开发的时候也遇到了这问题，可能是uni-app input的问题，自定义组件里input只要有@input事件，页面引用了这个组件，就会在input失去焦点的时候报错，目前解决方法是在引用了自定义组件的页面内写一个同名的@input 空方法，比如在用了u-input组件的页面内声明一个空的handleInput方法。

**Comment by chenjiecloud** [comment]
确实可以解决input失去焦点报错的问题
