### ISSUE TITLE
建议选择器u-select的confirm支持传参

### ISSUE THREAD

**Issue by Jarvis-Liu** [umicro/uView#355]
rt，在该回调中支持传参适用于同一页面多个u-select的场景，每个选择器都绑定同一个方法，利用传入的参数来区分更改对应的data，而无需在methods对应的给每一个u-select都声明一个confirm function

**Comment by qyhever** [comment]
> rt，在该回调中支持传参适用于同一页面多个u-select的场景，每个选择器都绑定同一个方法，利用传入的参数来区分更改对应的data，而无需在methods对应的给每一个u-select都声明一个confirm function

包一层就行了，@confirm="confirm"改成 @confirm="e => confirm(e, 'param')"
