### ISSUE TITLE
Select组件Bug

### ISSUE THREAD

**Issue by laozb** [umicro/uView#500]
官方小程序例子 select-列选择器 点击打开 滑动选到 ‘雨’选项下的‘十’选项 点击确认 select值：十   这是正确的，再次点击打开，不滑动，此时选中的是 ‘十’选项，但是点击确认，select值：雨   变成了雨
即 滑动选择后并确认一个值之后，再次打开不滑动直接点击确认，选中的值会变成默认值而不是上一次滑动并确认的值

**Comment by laozb** [comment]
setDefaultSelector和setSelectValue应该在setColumnData函数的最后一行 this.columnData = data; 之后执行，否则会出现picker-view的value改变但是组件渲染完成后没生效的问题

**Comment by yatoku** [comment]
#1173
