### ISSUE TITLE
支付宝小程序里不支持$slots，提示$slots.default报错

### ISSUE THREAD

**Issue by atishoo** [umicro/uView#535]
![image](https://user-images.githubusercontent.com/7723403/96008555-4284eb80-0e72-11eb-9bdd-a603b804995f.png)
貌似是支付宝小程序不支持$slots, 文件u-modal第8行使用到该变量导致控制台直接报错

**Comment by tttao7** [comment]
建议更新看看

**Comment by atishoo** [comment]
> 建议更新看看

依旧，最新版1.7.7

**Comment by MroZ11** [comment]
开启component2编译
[https://uviewui.com/components/changeGuide.html](升级指南1.5.4)

**Comment by yatoku** [comment]
#1159
