### ISSUE TITLE
picker mode = time 支付宝小程会奔溃，版本为1.7.3

### ISSUE THREAD

**Issue by chenyongta** [umicro/uView#611]
Cannot read property 'props' of null
Please check your axml: 
    in picker-view
    in view
    in view
    in scroll-view
    in view
    in view
    in /uview-ui/components/u-popup/u-popup
    in /uview-ui/components/u-picker/u-picker
    in view
    in view
    in view
    in pages/componentsB/picker/index

**Comment by Lv-Y-J** [comment]
请问你这个问题解决了吗？

**Comment by lovae** [comment]
1.8.2版本，还是有这个bug

**Comment by lovae** [comment]
> 请问你这个问题解决了吗？

我暂时用支付宝小程序官方API“my.datePicker”解决的

**Comment by lovae** [comment]
我暂时用支付宝小程序官方API“my.datePicker”解决的

**Comment by yatoku** [comment]
https://github.com/umicro/uView/pull/412
