### ISSUE TITLE
有更改内部样式的小技巧吗? 为什么组件的样式基本都改不掉

### ISSUE THREAD

**Issue by xsqcoder** [umicro/uView#638]

**Comment by haohaitao** [comment]
组件本地化，随意DIY

**Comment by BeiQiaoT** [comment]
组件样式的改变，一些文档都会给出案例。以对象的形式传入组件

**Comment by qinyao0817** [comment]
把 scoped 关掉 给父级class 然后通过选择器修改样式

**Comment by 79229788** [comment]
哎，这么好的组件库浪费了，作者居然敢用scoped，等同于封锁了自己的代码，但凡一家常用的第三方UI库，都不会用scoped，因为一旦用了这个，组件样式都无法在被修改了，虽然作者提供了custom-style，但是没啥意义，不是所有模块都有custom-style，而且伪元素和伪类没法修改。而一个标准的UI库，使用者或多或少都会修改，是一定会修改一些细节样式来达到和自己产品的主题保持一致，所以一款常用的开源的组件库是一定不会使用scoped

**Comment by Corgis** [comment]
就说怎么总是改不动

**Comment by Corgis** [comment]
就说怎么一直改不掉
