### ISSUE TITLE
checkboxGroup  checkbox 有bug，搭配搞个批量选择取消的时候，居然逻辑是相反的，具体你们自己检测

### ISSUE THREAD

**Issue by bbzhengcheng** [umicro/uView#67]
checkboxGroup  checkbox 有bug，搭配搞个批量选择取消的时候，居然逻辑是相反的，具体你们自己检测

**Comment by BeiQiaoT** [comment]
> checkboxGroup checkbox 有bug，搭配搞个批量选择取消的时候，居然逻辑是相反的，具体你们自己检测

已记录
