### ISSUE TITLE
upload组件中回显渲染重复url渲染问题

### ISSUE THREAD

**Issue by Longder** [umicro/uView#704]
upload组件中file-list绑定的数组里，有多个对象，但是对象的url是同一个，这种情况下是不是渲染出来还是只有一个？能否重复地显示渲染多个？
![image](https://user-images.githubusercontent.com/7322594/101875508-b703ae80-3bc5-11eb-9a74-54001d7090cd.png)
![image](https://user-images.githubusercontent.com/7322594/101875525-bc60f900-3bc5-11eb-886f-2e88138c9eca.png)

**Comment by Yooooooomu** [comment]
url加个时间戳什么的可以解决

**Comment by yatoku** [comment]
> upload组件中file-list绑定的数组里，有多个对象，但是对象的url是同一个，这种情况下是不是渲染出来还是只有一个？能否重复地显示渲染多个？ ![image](https://user-images.githubusercontent.com/7322594/101875508-b703ae80-3bc5-11eb-9a74-54001d7090cd.png) ![image](https://user-images.githubusercontent.com/7322594/101875525-bc60f900-3bc5-11eb-886f-2e88138c9eca.png)

![image](https://user-images.githubusercontent.com/35695074/202384657-73a4edb0-eae1-4b71-be7e-244e5601e1a7.png)
