### ISSUE TITLE
u-button的plain没有效果

### ISSUE THREAD

**Issue by Linpengfei-NB** [umicro/uView#714]
u-button的plain没有效果

**Comment by BeiQiaoT** [comment]
> u-button的plain没有效果

plain是正常可用的，您检查一下你的css有没有冲突哦

**Comment by Linpengfei-NB** [comment]
> > u-button的plain没有效果
> 
> plain是正常可用的，您检查一下你的css有没有冲突哦

<u-button type="default" open-type="share" class="share-btn" :plain="true" style="height: 100px;">
  <image class="image image-3" :src="`${$sourcePath}/report/btn.png`" open-type="share" @click="share" mode=""></image>
</u-button>

![image](https://user-images.githubusercontent.com/38002558/102458500-4d7d1780-407f-11eb-9228-9f67af0908b9.png)
![image](https://user-images.githubusercontent.com/38002558/102458514-52da6200-407f-11eb-911e-fdd3bb32d859.png)

但是不使用u-button ,使用button就对了

**Comment by BeiQiaoT** [comment]
> u-button的plain没有效果
> plain是正常可用的，您检查一下你的css有没有冲突哦
> 
> 
> 
> 
> 
> 但是不使用u-button ,使用button就对了

你看一下官方案例，的确是可以用的

**Comment by Linpengfei-NB** [comment]
> > u-button的plain没有效果
> > plain是正常可用的，您检查一下你的css有没有冲突哦
> > 但是不使用u-button，使用button就对了
> 
> 你看一下官方案例，的确是可以用的

你可以去看一下，微信小程序有uview的官方小程序样例。加了plain只是背景色颜色变了。
