### ISSUE TITLE
u-select    默认值希望不要用下标，直接用value

### ISSUE THREAD

**Issue by qeprwjcgya** [umicro/uView#745]
u-select   多列联动模式 默认值希望不要用下标，直接用value数组，
因为数据库里面存的是value,如果用下标来默认的话的，还要去遍历，很麻烦啊

**Comment by BeiQiaoT** [comment]
> u-select   多列联动模式 默认值希望不要用下标，直接用value数组，
> 
> 因为数据库里面存的是value,如果用下标来默认的话的，还要去遍历，很麻烦啊

返回下标可以满足绝大多数需求，反之不然。

**Comment by qeprwjcgya** [comment]
我是从事后端开发的，从表设计的角度来看，数据库肯定存的是value,如果默认是value的话，直接就可以用了，下标虽然通过，但是更多的场景是使用value,如果是省市区这种级联默认，用下标来设置默认值，要循环遍历的呢。代表个人观点。也可以在一些技术群里作个问卷调查。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YanxinNet/uView"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月30日(星期三) 凌晨0:45
收件人:&nbsp;"YanxinNet/uView"<uView@noreply.github.com&gt;;
抄送:&nbsp;"_Bean.Woo"<158921300@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YanxinNet/uView] u-select    默认值希望不要用下标，直接用value (#745)





  
u-select   多列联动模式 默认值希望不要用下标，直接用value数组，
 
因为数据库里面存的是value,如果用下标来默认的话的，还要去遍历，很麻烦啊
  
返回下标可以满足绝大多数需求，反之不然。
