### ISSUE TITLE
使用封装的vuex后如何在js文件中读取到全局变量

### ISSUE THREAD

**Issue by liquanhui-99** [umicro/uView#785]
项目中使用了框架分装好的全局变量设置，vue文件中template部分可以正常的获取到变量的值，js部分也可以修改变量对应的值，但是如何在js部分直接获取全局变量的值？而不是修改

**Comment by liquanhui01** [comment]
怎么没有人回复，加qq也不通过，这问题怎么解决？

**Comment by yatoku** [comment]
如果不是想要实时对应的数据的话，可以从缓存中获取
![image](https://user-images.githubusercontent.com/35695074/215690434-fb076797-4bc8-46f5-ab5f-a6c683c54247.png)
