### ISSUE TITLE
关于toast 需配合模板使用的疑问

### ISSUE THREAD

**Issue by Corgis** [umicro/uView#787]
u-toast是否有 类似 uni.showToast  直接调用的方法，
比如我有个需求 是在请求的响应拦截里去弹错误提示  如果必须配合模板使用，那我要如何去调用呢？

**Comment by shilianmalaxiangguo** [comment]
同问，想知道解决办法

**Comment by gcindy** [comment]
解决了嘛？

**Comment by yatoku** [comment]
没有类似的调用方式

**Comment by yatoku** [comment]
> 同问，想知道解决办法

可以尝试，使用这个框架来实现https://github.com/umicro/uniapp-router-view-loader
