### ISSUE TITLE
ios 10.2 使用Vue.use(uView) 页面白屏

### ISSUE THREAD

**Issue by syymo** [umicro/uView#801]
import uView from "uview-ui";
Vue.use(uView);  // 去掉后页面正常显示

Date: 2021/1/26下午9:14:09.420 (LogID: mqc)
SyntaxError: Unexpected keyword 'new'. Expected ';' after variable declaration.
Unexpected keyword 'new'. Expected ';' after variable declaration.
Page Url: 
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1

ios10.2 白屏

**Comment by zbl400** [comment]
这个问题解决了吗？我也碰到了。
一摸一样的 ios 10.2 , 
一样的 SyntaxError: Unexpected keyword 'new'. Expected ';' after variable declaration.
根据行数找到的是 这行
const isNext = await new Promise((resolve, reject) => {

**Comment by syymo** [comment]
> 这个问题解决了吗？我也碰到了。
> 一摸一样的 ios 10.2 ,
> 一样的 SyntaxError: Unexpected keyword 'new'. Expected ';' after variable declaration.
> 根据行数找到的是 这行
> const isNext = await new Promise((resolve, reject) => {

问题解决了，用babel再把uview编译一次，vue.config.js加入这个：
```
// u-view Unexpected keyword 'new'. Expected ';' after variable declaration.  解决方法
transpileDependencies: [
    /[/\\]node_modules[/\\]uview-ui[/\\]/,
]
```
