### ISSUE TITLE
作者大大能取消scoped吗？修改起来很难受

### ISSUE THREAD

**Issue by Dullly** [umicro/uView#812]
scoped限制了修改

**Comment by BeiQiaoT** [comment]
> scoped限制了修改

现在已经几乎是没法改了，在uView2.0中，我们会对此进行去除

**Comment by NidhoggDJoking** [comment]
> > scoped限制了修改
> 
> 现在已经几乎是没法改了，在uView2.0中，我们会对此进行去除

希望作者可以抽空回复下大家提出的问题，现在的问题是越积越多了。

**Comment by Dullly** [comment]
您好~~您的邮件我已收到，会尽快给您进行回复~~
