### ISSUE TITLE
Search 搜索组件没有 clear 事件

### ISSUE THREAD

**Issue by fengHeart** [umicro/uView#82]
clearabled 属性开启后有清除控件的 icon ，却没有 clear 事件！！！

**Comment by BeiQiaoT** [comment]
> clearabled 属性开启后有清除控件的 icon ，却没有 clear 事件！！！

已经确认，记录了

**Comment by YanxinNet** [comment]
1. 请不要激动，文档从来没有说过配置了clearabled之后(默认配置了此参数，会出现清除图标，可以清空输入框内容)，就会发出clear事件。
2. 已在1.3.3版本加入了clear事件。

**Comment by Dream-feng** [comment]
@YanxinNet 现在已经有 clear 事件，不过为什么 clear 事件的触发会比 v-model 还有快？是否可以解决这个问题？
![image](https://user-images.githubusercontent.com/41051203/84559431-2579c800-ad6d-11ea-87bf-41468a9ca35a.png)
![image](https://user-images.githubusercontent.com/41051203/84559449-3e827900-ad6d-11ea-95ec-b31c194d288b.png)
