### ISSUE TITLE
使用 sass-loader v11.0.1 版本报错，v10 版本则正常

### ISSUE THREAD

**Issue by 1014156094** [umicro/uView#831]
![image](https://user-images.githubusercontent.com/16074662/108465568-3d6ef780-72bd-11eb-851d-5a6f035d0921.png)

 ERROR  Failed to compile with 1 error                                                          下午2:17:24
 error  in ./src/App.vue?vue&type=style&index=0&lang=scss&

Syntax Error: TypeError: this.getOptions is not a function

 @ ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/h5-vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-2!./node_modules/postcss-loader/src??ref--8-oneOf-1-3!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-4!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--8-oneOf-1-5!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-scoped-loader!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/wrap-loader??ref--17!./src/App.vue?vue&type=style&index=0&lang=scss& 4:14-824 14:3-18:5 15:22-832
 @ ./src/App.vue?vue&type=style&index=0&lang=scss&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.26:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by zhangchenna** [comment]
sass-loader v11 不支持webpack4 肯定会报错
