### ISSUE TITLE
文档缺少组件按需引入的教程

### ISSUE THREAD

**Issue by 1014156094** [umicro/uView#833]
如题

**Comment by weijiatan456** [comment]
有：https://uviewui.com/components/setting.html

**Comment by 1014156094** [comment]
文档的是导入所有组件，不是按需引入
![image](https://user-images.githubusercontent.com/16074662/108489463-8b472800-72dc-11eb-872a-6afb49b9f4e5.png)

参考 vant-ui https://vant-contrib.gitee.io/vant/#/zh-CN/quickstart#fang-shi-san.-dao-ru-suo-you-zu-jian
![image](https://user-images.githubusercontent.com/16074662/108577438-0996df00-735c-11eb-90c6-3c079caaf2a1.png)

**Comment by caidesen** [comment]
通过 easycom 实现的按需引入，和 vant ui 不同

**Comment by 1014156094** [comment]
噢噢
