### ISSUE TITLE
u-select选择项错误

### ISSUE THREAD

**Issue by kubahai** [umicro/uView#870]
打开后滚动选择非第一条，然后关闭再打开，选项停留在上一次选择中，不滚动直接点击确定，选中的确实第一条

**Comment by XansamLin** [comment]
遇到同样的问题

**Comment by XansamLin** [comment]
如果不想改源码，可以自己先维护一个defaultValueIndex，每次获取到u-select选中的值后，设置defaultValueIndex为选中项在选项列表中的下标值，然后传入u-select的default-value属性。

**Comment by XansamLin** [comment]
已收到您的邮件，我会尽快处理！
