### ISSUE TITLE
支付宝小程序报错TypeError: Cannot read property 'default' of undefined"

### ISSUE THREAD

**Issue by yan66666666** [umicro/uView#900]
支付宝插槽问题
我看1.8.2版本解决了这个问题
 v-if="$slots.default || $slots.$default"
但是还是报错
![image](https://user-images.githubusercontent.com/55675765/114367949-881b3a80-9baf-11eb-935e-af6ac8dd9a7f.png)

**Comment by jzsn2018** [comment]
我也遇到同样的问题了,请问你解决了吗

**Comment by Panpan-GitHub** [comment]
我也遇到了一样的问题，再支付宝小程序里用u-slider的时候$slot报undefinde

**Comment by yatoku** [comment]
#1159
