### ISSUE TITLE
uview太大了，导致小程序预览的时候超出大小，怎么解决啊

### ISSUE THREAD

**Issue by CodeInn1024** [umicro/uView#919]
uview太大了，导致小程序预览的时候超出大小，怎么解决啊

**Comment by CodeInn1024** [comment]
我使用cli，npm使用的

**Comment by 851091009** [comment]
分包: https://uniapp.dcloud.io/collocation/pages?id=subpackages

**Comment by BigGuang** [comment]
同样的情况，dcloud官方给的分包只是分pages，npm方式下的uview直接就占了将近4MB
希望uview官方能给个解决方案

**Comment by BigGuang** [comment]
和你碰到了一样的问题，研究了很久发现打包后的wxss文件都很大，有重复的公共css。最后uni.scss里面变量可以保留，而其他的css 都放到app.vue里面。

**Comment by MichaelGaoX** [comment]
减少在uni.scss的样式，放入app.vue中。uni.scss的样式会导入每一个组件的scss中

**Comment by remember-5** [comment]
> 减少在uni.scss的样式，放入app.vue中。uni.scss的样式会导入每一个组件的scss中

按照这样使用，打包后，wxss还是很大
