### ISSUE TITLE
h5 设置捏滚动条隐藏，请问怎么配置显示滚动条？

### ISSUE THREAD

**Issue by 851091009** [umicro/uView#920]
隐藏的css：
![image](https://user-images.githubusercontent.com/8460036/115875316-ab7b9a80-a477-11eb-8376-34e16b2e1435.png)

**Comment by yatoku** [comment]
在`uview-ui/index.scss`中
注释掉这段代码
```
// H5特有的样式
/* #ifdef H5 */
@import "./libs/css/style.h5.scss";
/* #endif */
```
