### ISSUE TITLE
u-select组件如何开启待选搜索 ？

### ISSUE THREAD

**Issue by w263756314** [umicro/uView#921]
如果 u-select 有几十上百个选项，一个个找太费眼了，能不能有一个筛选功能，可以输入内容实时筛选待选项 ？
举个栗子：全校有几百位老师，表单里需要选择老师的名字，怎么快速定位到某位老师并选中 ？

**Comment by yatoku** [comment]
没有这个功能，有这个需求可以使用uniapp的ui https://uniapp.dcloud.net.cn/component/uniui/uni-combox.html
