### ISSUE TITLE
[需求] <u-input type="textarea"> 不能设置cursor 光标的位置  还有@blur 和@focus 获取不到光标位置 只返回了value 

### ISSUE THREAD

**Issue by zhandeze** [umicro/uView#949]
期望这样返回

> handleBlur(event) {
  ...
  this.$emit('blur', event)
  ...
},
onFocus(event) {
  this.focused = true;
  this.$emit('focus', event);
}

**Comment by yatoku** [comment]
大部分人都没有这个需求
