### ISSUE TITLE
uview 怎么区分 H5 与 安卓

### ISSUE THREAD

**Issue by old-boy** [umicro/uView#951]
我在你们的代码中看不到是怎么区分平台代码的？另外我使用命令打包，比如 npm run build:h5 也不能用，求指点，谢谢

**Comment by yatoku** [comment]
uview只是一个依附于uniapp的ui框架，除了部分平台差异化的代码以外是不需要区分平台的

**Comment by yatoku** [comment]
> 我在你们的代码中看不到是怎么区分平台代码的？另外我使用命令打包，比如 npm run build:h5 也不能用，求指点，谢谢

如果是在HBX的uniapp项目，直接发行
![image](https://user-images.githubusercontent.com/35695074/159219548-fbbf5ef3-06eb-49c2-b0bf-663b187f7b3b.png)
即可。
如果是uniapp-cli项目建议查看文档
