### ISSUE TITLE
uview组件from-item在小程序与h5里表现一不致

### ISSUE THREAD

**Issue by zhangdaren** [umicro/uView#956]
有代码：
`     <u-form class="from-submit" ref="uForm" label-width="160" :error-type="['toast', 'border-bottom']">  
            <u-form-item label="上课时间" prop="beginTime" class="u-flex" :required="true">  
                <view>xxx</view>  
                <text class="label-text">至</text>  
                <view>xxx</view>  
            </u-form-item>  
        </u-form>
`

在微信小程序与h5平台，表现不一致，具体见：

https://ask.dcloud.net.cn/article/39078

**Comment by yatoku** [comment]
看一下这个
https://www.kancloud.cn/uview/uview-ui_v2/2587980
