### ISSUE TITLE
uni-app cli的形式引入uview，编译H5在电脑端微信浏览器无法打开

### ISSUE THREAD

**Issue by ren2436** [umicro/uView#981]
uni-app使用cli的形式，引入uview，编译为H5，在电脑端微信浏览器打开报错
![image](https://user-images.githubusercontent.com/8308372/120624120-f0d9b180-c492-11eb-9aeb-721be8f53505.png)
关掉路由自定义拦截器后
![image](https://user-images.githubusercontent.com/8308372/120624552-647bbe80-c493-11eb-8c1a-1942d542a58a.png)
重新编译就没问题了
这个明显是 ES6未转ES5，查资料，说HBuilder自带ES6转ES5功能，但CLI形式需要自行安装，哪位大神知道安装什么插件即可无缝使用
@babel/cli  需要手动执行，显然不是很合适，或者需要如何配置在dev或build时自动转换

**Comment by yatoku** [comment]
在vue.config.js中
```js
// vue.config.js，如没有此文件则手动创建
module.exports = {
    transpileDependencies: ['uview-ui']
}
```
