### ISSUE TITLE
this.$u.route 函数可以自动判断是否是tabbar吗？ 建议加一个这个功能，不用手写type

### ISSUE THREAD

**Issue by huaiguoguo** [umicro/uView#982]
this.$u.route 函数可以自动判断是否是tabbar吗？ 建议加一个这个功能，不用手写type
type可以保留，如果没有写，就自动判断当前页面是不是 tabbar，如果是tabbar就用switchTab

**Comment by gapkukb** [comment]
使用官方的uni方式跳转，因为uni的方式支持错误回调。我的处理方式是uni失败回调中再换一个方式即可。

![image](https://user-images.githubusercontent.com/15757875/121977242-20a08780-cdb8-11eb-9cb3-01633aa6d8c1.png)

一定要设置settimeout，否则app会因为捕获报错而终止执行

**Comment by gapkukb** [comment]
没有考虑参数传递，可以拼接在url中，也可以自行扩展

**Comment by yatoku** [comment]
可以修改一下源码加一下tabbar页面的路径数组，然后跳转的时候做一下判断把类型修改成tabbar对应的
